#include <iostream>
#include <iomanip>
#include <cstdio>
#include <stdlib.h>
#include <string>
#include <algorithm>
#include <limits>
#include <vector>
using std::vector;
using std::swap;
using std::fixed;
using std::stoi;
using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::string;
using std::copy;
